runtime: nodejs10
handlers:
- url: /css
  static_dir: css
  secure: always
- url: /src
  static_dir: src
  secure: always
- url: /fonts
  static_dir: fonts
  secure: always
- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
