runtime: nodejs10
handlers:
- url: /css
  static_dir: css
  secure: always
- url: /src
  static_dir: src
  secure: always
- url: /fonts
  static_dir: fonts
  secure: always
- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
